/**
 * Prepares the npm-publishable UI library package by copying component sources
 * from src/components/ui-library/components/ to packages/ui-library/components/
 * and generating packages/ui-library/index.js.
 * Run from repo root: npm run prepare-package
 * Then publish: cd packages/ui-library && npm publish
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SRC_DIR = path.join(ROOT, "src", "components", "ui-library", "components");
const PKG_DIR = path.join(ROOT, "packages", "ui-library");
const PKG_COMPONENTS = path.join(PKG_DIR, "components");

if (!fs.existsSync(SRC_DIR)) {
  console.error("Source dir not found:", SRC_DIR);
  process.exit(1);
}

if (!fs.existsSync(PKG_DIR)) {
  fs.mkdirSync(PKG_DIR, { recursive: true });
}
if (!fs.existsSync(PKG_COMPONENTS)) {
  fs.mkdirSync(PKG_COMPONENTS, { recursive: true });
} else {
  const existing = fs.readdirSync(PKG_COMPONENTS);
  for (const f of existing) {
    fs.unlinkSync(path.join(PKG_COMPONENTS, f));
  }
}

const files = fs.readdirSync(SRC_DIR).filter((f) => f.endsWith(".js"));
const exportList = [];

for (const file of files) {
  const srcPath = path.join(SRC_DIR, file);
  const destPath = path.join(PKG_COMPONENTS, file);
  const name = path.basename(file, ".js");
  fs.copyFileSync(srcPath, destPath);
  exportList.push({ name, file });
  console.log("Copied", file);
}

const indexLines = [
  "// Mutate UI – auto-generated by scripts/prepare-package.js",
  ...exportList.map(({ name, file }) => `export { default as ${name} } from './components/${file.replace(".js", "")}';`),
];
if (exportList.some((e) => e.name === "MutateInputField")) {
  indexLines.push("export { MutateTextInputField, MutateNumberInputField } from './components/MutateInputField';");
}

fs.writeFileSync(path.join(PKG_DIR, "index.js"), indexLines.join("\n"), "utf8");
console.log("Wrote packages/ui-library/index.js");
